version: 2

models:
  - name: stg_outcomes
    config:
      tags: "ivr_prompt"
    description: This table displays the different outcomes reached via the program 
    columns:
      - name: outcome_id
        description: Primary Key for outcomes and named as outcome_id
      - name: spectrum
        description: Time duration on when to implement the outcome_name
      - name: outcome_name
      - name: count_of_indicators
        description: column used to map outcomes table from indicators table
  - name: stg_indicators
    config:
      tags: "ivr_prompt"
    description: Describes user attributes sub categorized into different topics
    columns:
      - name: indicator_id
        description: Primary Key for table `indicators` and named as indicator_id
        tests:
          - unique
          - not_null
      - name: type
        description: User Attributes
      - name: outcome_id
        description: outcome id mapped to indicators_name
      - name: indicator_name
        description: Name of the indicator
      - name: outcome_name_lookup
        description: This column is only used to map the indicator table
      - name: outcome_spectrum_lookup
        description: This column is only used to map the indicator table
      - name: count_of_questions_mapped
        description: This column is only used to map the indicator table
  - name: stg_questions
    config:
      tags: "ivr_prompt"
    description: This table tells us what questions will be asked as a prompt over the call in the program
    columns:
      - name: question_id
        description: Primary Key for table 'questions' and named as question_id
        tests:
          - unique
          - not_null
      - name: status
        description: This columns tells us whether the question is active or not as prompt question
      - name: short_name
      - name: indicator_id
        description: Indicator table mapped to the questions
      - name: question_hindi
        description: Questions used as a prompt in Hindi Language
      - name: activation_date
        description: When was the question got activated for the respective program
      - name: evaluation_phase
        description: questions that are directed to the user at different level of programs 
      - name: question_english
        description: Questions used as a prompt in English Language
      - name: deactivation_date
        description: The date at which the question got deactivated from the program
      - name: count_of_placements
        description: This column tells us how many questions are there at a particular evaluation phase
      - name: count_of_configured_responses
        description: This column tells us how many responses have been mapped to a particular question
  - name: stg_question_placement
    config:
      tags: "ivr_prompt"
    description: This table shows what questions are mapped to what table of the data model in the program
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - unified_content_map_id
            - data_source
            - question_placement_activation_date
            # - question_deactivation_date
    columns: 
      - name: question_placement_id
        description: Primary Key for table 'question placements' and named as question_placement_id
        tests:
          - unique
          - not_null
      - name: status
        description: This column tells you the status of question placements 
      - name: content_id
        description: This column tells you what content is mapped to what questions
      - name: data_source
        description: The columns show what data source that is being used 
      - name: question_id
        description: The columns show what questions are mapped
      - name: activation_date
        description: When was the question got activated
      - name: deactivation_date
        description: When was the question got deactivated
      - name: program_sequence_id
        description: This column shows what program sequence id is mapped
  - name: stg_configured_responses
    config:
      tags: "ivr_prompt"
    description: The tables shows the responses that are being mapped to their respective questions
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - question_id
            - keypress
    columns:
      - name: response_id
        description: Primary Key for table 'configured responses' and named as response_id
        tests:
          - unique
          - not_null
      - name: keypress
        description: This column shows what key number the user has given
      - name: short_name
        description: Short Name of the entire program(question, content, evaluation phase)
      - name: question_id
        description: Question id mapped to the answer a user has given by pressing the key
      - name: response_eng
        description: Response of the user in English
      - name: response_hin
        description: Response of the user in Hindi
      - name: desired_response
        description: The response that is desired from the user
      - name: webhook_resp_val
